PAGE_ICON = ":books:"
PAGE_TITLE = "MEF-DB1 - Chat with your PDFs"
PDF_UPLOAD_MSG = "Upload your PDFs here and click on 'Process'"
PROCESSING_MSG = "Processing"
SUB_HEADER_TEXT = "Your documents"
HEADER_TEXT = "Chat with your PDFs :books:"
TEXT_INPUT_PROMPT = "Ask a question about/to your documents:"
